/* Sidebar Reducer Types */
export const ACTIVATE_ALL_SIDEBARS = "ACTIVATE_ALL_SIDEBARS";
export const ACTIVATE_NO_SIDEBARS = "ACTIVATE_NO_SIDEBARS";
export const ACTIVATE_ONLY_LEFT_SIDEBAR = "ACTIVATE_ONLY_LEFT_SIDEBAR";
export const ACTIVATE_ONLY_RIGHT_SIDEBAR = "ACTIVATE_ONLY_RIGHT_SIDEBAR";

/* File Reducer */
export const LOAD_FILE_INPUT = "LOAD_FILE_INPUT";